version: "2.4"

volumes:
  stat: ~

services:
  nginx:
    image: nginx:1.17.3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      wordpress:
        condition: service_started
      mariadb:
        condition: service_started
      telegraf:
        condition: service_started
      influxdb:
        condition: service_started

  wordpress:
    build: .
    entrypoint: /bin/entrypoint
    volumes:
      - stat:/var/run
      - ./php-entrypoint.sh:/bin/entrypoint
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    healthcheck:
      test: bash -c "</dev/tcp/localhost/3306"

  telegraf:
    image: telegraf:1.11
    volumes:
      - stat:/var/run
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb:1.7
    healthcheck:
      test: bash -c "</dev/tcp/localhost/8086"

  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    ports:
      - 8888:8888
    depends_on:
      influxdb:
        condition: service_healthy
